version: '3'
services:
  # Serviço do aplicativo Nest.js
  api:
    build:
      context: .
      dockerfile: Dockerfile # Nome do seu Dockerfile
    ports:
      - "3000:3000" # Porta do aplicativo Nest.js

  # Serviço do banco de dados MongoDB
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017" # Porta padrão do MongoDB

  # Outros serviços podem ser adicionados conforme necessário
