version: '3'

services:
  nestjs:
    build: ./
    container_name: orientaunb_api
    environment:
      - PORT=3000
      - SERVICE_TITLE=Orienta UnB Api
      - SERVICE_DESCRIPTION=Orienta UnB Api
      - SERVICE_VERSION=0.1.0
      - SERVICE_TAG=1
      - MONGO_DATABASE=orientaDB-dev
      - MONGO_USER=hufflepuff
      - MONGO_HOST=orientaunbdevcluster.enczr6j.mongodb.net
      - MONGO_PASSWORD=Ei0CLjRVN3aexFOj
      - JWT_SECRET_KEY=P2LLSukoCUFpIuQjNYeQd2m5nAasDnEFmnp9DAsO/sU=
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    networks:
      - orientaunb_networks

  mongodb:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-volumes:/data/db
    networks:
      - orientaunb_networks

networks:
  orientaunb_networks:
