version: '3'
services:
  # Serviço do aplicativo Nest.js
  api:
    build:
      context: .
      dockerfile: Dockerfile # Nome do seu Dockerfile
    ports:
      - '${PORT}:${PORT}'
    networks:
      - backend
    env_file:
      - .env

  api-dev:
    container_name: api_dev_container
    build: .
    hostname: api_service
    command: npm run start:dev
    volumes:
      - .:/var/www/server
    ports:
      - '${PORT}:${PORT}'
    networks:
      - backend
    env_file:
      - .env

  api-debug:
    container_name: api_debug_container
    build: .
    hostname: api_service
    command: npm run start:debug
    volumes:
      - .:/var/www/server
    ports:
      - '${PORT}:${PORT}'
      - '9229:9229'
    networks:
      - backend
    env_file:
      - .env

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017' # Porta padrão do MongoDB


  # Outros serviços podem ser adicionados conforme necessário
