version: '3.5'

services:
  api-prod:
    container_name: api_prod_container
    build: .
    hostname: api_service
    command: npm run start:prod
    volumes:
      - .:/app
    ports:
      - '${PORT}:${PORT}'
    networks:
      - backend
    env_file:
      - .env

  api-dev:
    container_name: api_dev_container
    build: .
    hostname: api_service
    command: npm run start:dev
    volumes:
      - .:/app
    ports:
      - '${PORT}:${PORT}'
    networks:
      - backend
    env_file:
      - .env

  api-debug:
    container_name: api_debug_container
    build: .
    hostname: api_service
    command: npm run start:debug
    volumes:
      - .:/app
    ports:
      - '${PORT}:${PORT}'
      - '9229:9229'
    networks:
      - backend
    env_file:
      - .env

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    networks:
      - backend

networks:
  backend:
    name: orienta_network
    driver: bridge

volumes:
  mongo_data:
